### ISSUE TITLE
War deployment issue

### ISSUE THREAD

**Issue by Kabenla** [EBISPOT/OXO#22]
I managed to clone and compile the application, but when I deploy the WAR file to my tomcat instance I get the error shown in the attachment

![3 kabenla ebispt-ols-mumping ssh 2018-05-31 12-09-00](https://user-images.githubusercontent.com/5950671/40796694-87cd0f18-64cb-11e8-8ee1-01f0b047d777.png)

**Comment by simonjupp** [comment]
You need an application.properties file in https://github.com/EBISPOT/OLS-mapping-service/tree/master/oxo-web/src/main/resources then rebuild with maven. 

You'll have to configure this to use your own neo4j url and password, location of solr server and path where the hsqldb will be stored. 

```
logging.level.org.springframework.web: ERROR
endpoints.enabled=false
logging.level.org.neo4j.ogm: ERROR
logging.level.uk.ac.ebi.spot: INFO
security.user.password: test

oxo.indexer.chunks 50000
oxo.neo.driver=org.neo4j.ogm.drivers.http.driver.HttpDriver

oxo.neo.uri=http://neo4j:password@localhost:7474

spring.data.solr.host: http://localhost:8983/solr

oxo.access.readonly true
logging.level.org.springframework.security: INFO

# DataSource
spring.datasource.url: jdbc:hsqldb:file:<path save hsqldb files>/hsqldb
spring.jpa.hibernate.ddl-auto: update
```

**Comment by Kabenla** [comment]
Thanks a lot Simon, I will give this a shot

**Comment by simonjupp** [comment]
If that didn't resolve your issue please re-open the ticket.
