### ISSUE TITLE
Mappings for ICD10 and self-reported traits must be in OxO (please)

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OXO#24]
A priority because of Bioontologies conference paper and as requested by Helen. Ideally, all the mappings should be in OxO at the point of review.

**Comment by daniwelter** [comment]
This requires an OXO rebuild. To be done by Simon before the Bioontologies paper deadline (11/04/19).

**Comment by twhetzel** [comment]
@paolaroncaglia to check if the mappings are in OxO with a few of the ICD10 mappings as an example

**Comment by paolaroncaglia** [comment]
@zoependlington @henrietteharmse 
When did you say OxO was last built please?
I checked the following:

1) ICD10:Z89 mapped to EFO:0009632 amputation (EFO term created ~1/2/19) => yes it's in OxO, as expected

2) ICD10:Z32 mapped to EFO:0009643 pregnancy test (EFO term created ~11/2/19) => yes it's in OxO, as expected

3) ICD10:Z60 mapped to EFO:0009788 encounter with health service related to socioeconomic and psychosocial circumstances (EFO term created ~8/4/19) => no it's in OxO (we know that OxO was lastly built after 4/4/19, so that could be ok) 

4) ICD10:C78 mapped to EFO:0009812 secondary malignant neoplasm (EFO term created 16/4/19) => no it's in OxO, as expected

Let me know if you'd like me to test more. Otherwise the ticket can be moved to Done, thanks.

**Comment by simonjupp** [comment]
OxO updates on the first Saturday of every month, so check again on May 6th.

**Comment by paolaroncaglia** [comment]
As of today May 6th, the last two mappings listed in my previous comment are in OxO. I suppose this ticket can be closed (I'll move to "Done" for now).
