### ISSUE TITLE
Add LOINC please

### ISSUE THREAD

**Issue by turbomam** [EBISPOT/OXO#27]
Hello Simon and colleagues. OxO is great. Thanks.

Have you thought about adding LOINC? 

The PennTURBO team is making a realism based semantic graph of electronic health records, using terms from OBO foundry ontologies. For instantiating laboratory results, we need to map from LOINC parts like system and component to material entities with evaluant and analyte roles (like bodily fluids, chemicals and cells). BioPortal has pretty good mappings from LOINC to ChEMBL and Uberon, but the mappings to the Cell Ontology seem less complete.

thanks,
Mark

**Comment by henrietteharmse** [comment]
Hey Mark!
No, we have not, but this certainly seems like a good idea. I will discuss this with my colleagues and get an idea of how feasible this is. I will let you know as soon as I can.
Keep well.

**Comment by udp** [comment]
Hi @turbomam, just an update on this.  We have been prototyping a LOINC loader for OxO and so far it looks promising.  I'll keep you informed, and hopefully we will have something for you to try out soon!

**Comment by turbomam** [comment]
Thanks for the updates. Sorry for the slow response.

**Comment by udp** [comment]
Hi, the part related code mappings distributed with LOINC are now available in OXO:

https://www.ebi.ac.uk/spot/oxo/datasources/LNC

However, this only seems to be to SNOMED-CD and ChEBI. Do you have any recommendation for a datasource we can use for mappings to the Cell Ontology?

**Comment by turbomam** [comment]
I'm in a new role now and probably won't need the LOINC mappings. Apologies for not speaking up sooner.

I agree that Cell Ontology mappings are tricky. WHen I really needed them, I just did them lexically in real time with something like the OLS search.
