### ISSUE TITLE
Add top-level readme to repository

### ISSUE THREAD

**Issue by cthoyt** [EBISPOT/OXO#29]
It would be good to know if this project is dead or not. It looks like it is, but I saw there were other comments happening on the issues.

**Comment by henrietteharmse** [comment]
@cthoyt  Good idea. We will do that. BTW, this project is definitely not dead!

**Comment by dhimmel** [comment]
A top-level readme was added in https://github.com/EBISPOT/OXO/commit/ff8ab6f6c220457268d00a78b2faa6db8bc3cc31.

> BTW, this project is definitely not dead!

Glad to hear! Just learned about it and am excited to check it out.
