### ISSUE TITLE
Deploy publicly available OxO dev-instances

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OXO#31]
For our current use case, we urgently need to be able to fire up an instance of OxO that is accessible by a collaborator, to demonstrate certain features of OxO on a dataset not yet available for integration in primary OxO. Furthermore, as OxO development will restart again soon, we need to be able to test new features of OxO and share them with users before they are deployed in production. The definition of done for this ticket is:

- [ ] There are clear instructions on how to deploy a dev instance
- [ ] One OxO dev instance has been deployed according to the instructions and accessed by our collaborators

Note, while this is highly desirable, I think the question of making it possible to deploy OxO with docker should be treated separately, but I leave this decision up to @henrietteharmse

**Comment by henrietteharmse** [comment]
The dev instance will not be publicly available. The dev instance is purely for testing purpose.

**Comment by matentzn** [comment]
Sure we need an internal one that is not accessible, but we do need one that can be accessed by our collaborators as well!

**Comment by matentzn** [comment]
Not necessary anymore, using docker setup.
