### ISSUE TITLE
Collaborator inquiry: best way to deploy OxO

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OXO#32]
@henrietteharmse @udp meet @jamesoverton , one of the powerhouses of the OBO world. We need to, relatively timely, figure out what branch we should be using to deploy OxO to build whatever is on prod. Is it possible to give @jamesoverton some pointers where the most up to date instructions are, and which branch to use? Right this moment he does not use docker, so ideally, he gets the instructions for how to do it the normal, non-docker way. Thanks guys!

**Comment by jamesaoverton** [comment]
Thanks Nico. My GitHub username is @jamesaoverton with an "a". Sounds more impressive, no? :smile:

I'm working with @mcourtot on data harmonization for IHCC. I set up an OLS instance last week (< 193.62.55.169:8080/index>) with @matentzn's help, and now I would like to set up an OxO instance. More details in our issue:

https://github.com/IHCC-cohorts/data-harmonization/issues/45

I haven't started on OxO yet. If you have any tips, please let me know.

**Comment by henrietteharmse** [comment]
Unfortunately there is no existing documentation for this. @udp is in the process of writing clear instructions up which you can find the loinc branch where readme docs can be found in the root as well the oxo-loader directories.

**Comment by jamesaoverton** [comment]
Thanks @henrietteharmse, I'll use the `loinc` branch and let you know if I have useful feedback. Feel free to close this now.
