### ISSUE TITLE
REST API documentation partially broken

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/OXO#35]
Many of the examples in https://www.ebi.ac.uk/spot/oxo/docs/api seem to be broken as they show the following message where code is expected:

> Unresolved directive in api.adoc - include::/nfs/production3/spot/tools/Bamboo-home/xml-data/build-dir/OXO-BA-JOB1/oxo-web/src/main/asciidoc/generated-snippets/api-example/curl-request.adoc[]

![Screenshot 2020-06-18 at 09 47 51](https://user-images.githubusercontent.com/11410715/84999283-db1b9100-b148-11ea-9220-5f6ea526eb9e.png)

**Comment by udp** [comment]
Thanks Asier, this will be fixed in the next update.
