### ISSUE TITLE
null bug

### ISSUE THREAD

**Issue by kyook** [EBISPOT/OXO#44]
There seem to be some 'null'  issues with your site. 

![Screen Shot 2020-10-27 at 12 45 40 AM](https://user-images.githubusercontent.com/611610/97258350-a2727f00-17ee-11eb-93c1-d60799706fcd.png)
![Screen Shot 2020-10-27 at 12 45 47 AM](https://user-images.githubusercontent.com/611610/97258352-a3a3ac00-17ee-11eb-869b-6237a1e45762.png)
![Screen Shot 2020-10-27 at 12 46 01 AM](https://user-images.githubusercontent.com/611610/97258357-a56d6f80-17ee-11eb-8d38-040ec6ba01f9.png)

**Comment by henrietteharmse** [comment]
Can you please supply the exact link you used to access OxO when you received these null errors?

**Comment by kyook** [comment]
https://www.ebi.ac.uk/spot/oxo/search

**Comment by henrietteharmse** [comment]
We cannot reproduce this. I.e., this is what I get to do this:
![image](https://user-images.githubusercontent.com/32327979/97314638-d1750900-185f-11eb-9d9f-dc6e5089c7d8.png)

This looks like it may be a caching issue on your side. A clue to this is that it shows the old site partially. Here are things to check:
(1) Clear you browser cache and retry.
(2) If you have a different browser on your computer, you can try using that instead.

**Comment by matentzn** [comment]
When I go here: https://www.ebi.ac.uk/spot/oxo/search

![image](https://user-images.githubusercontent.com/7070631/97320513-ca50f980-1865-11eb-8f91-4abef3d3a2dd.png)

**Comment by matentzn** [comment]
And I refreshed it with hard reload and cashing. Could it be a networking thing?

**Comment by henrietteharmse** [comment]
Ah, so you are going directly to https://www.ebi.ac.uk/spot/oxo/search instead of going to https://www.ebi.ac.uk/spot/oxo, typing in your search details, then press the "Find mappings" button.

**Comment by kyook** [comment]
thank you @henrietteharmse, yes, that was the problem.  apologies, but I'm glad it ended up simple.
