### ISSUE TITLE
OXO Image stable missing

### ISSUE THREAD

**Issue by rpandey19** [EBISPOT/OXO#53]
I am trying to follow the steps for 'OXO with docker' and within the loader instructions it mentions the image 'ebispot/oxo-loader:stable'. However the stable tag image doesnt exists on docker hub. The only one I can find is with dev tag.

**Comment by udp** [comment]
Many apologies - I have been setting up automated deployment of the latest images and it hadn't fired because I accidentally had the task set to manual. The stable image is now in Docker Hub and good to go.

**Comment by rpandey19** [comment]
Thanks so much for quick response. I see the image now. will give it a try.

**Comment by rpandey19** [comment]
I was able to get the stable tag image
