### ISSUE TITLE
Search dropdowns does not populate

### ISSUE THREAD

**Issue by rpandey19** [EBISPOT/OXO#58]
In the local installation of OXO with docker the drop down are empty. They don't populate.
Search OxO by term id. -> Choose a target
Jump directly to a datasource

Please advice.

**Comment by matentzn** [comment]
This is too little information to support you. Can you describe exactly the steps you did to arrive at your installation? Is it possible your OLS is simply empty and does not have xrefs, so your OxO also does not?
