### ISSUE TITLE
Lisensing

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OXO#64]
Based on email from Helen:

Individual Resource pages - make sure resources you manage have licensing details displayed prominently, are unambiguous (eg don't refer to EBI general terms of use in one place and cc0 in another) and are up to date. https://www.ebi.ac.uk/licencing has some boilerplate text on licensing to reuse if required.

Due end of March 2023.

**Comment by serjoshua** [comment]
Link to licensing exists but we could re-open this ticket if there is a need to display it differently.

![Screen Shot 2023-03-09 at 11 38 19 AM](https://user-images.githubusercontent.com/25520595/224013346-04a8a157-5233-4e3a-b914-83d4516a4646.png)
